---
# tasks file for instance.openvpn_create_user_config
- name: Get local ec2 facts.
  ec2_facts:
  register: ec2_facts

- name: Debug local IP address.
  debug:
    msg: "{{ ansible_ec2_local_ipv4 }}"

- name: Get public IP for OpenVPN remote configuration.
  set_fact:
    openvpn_remote: "{{ groups['openvpn-public'][0] }}"

- name: Create user keys.
  shell: |
    docker exec openvpn \
    /bin/bash -c 'cd /etc/openvpn && \
    source ./vars && \
    ./build-key-automated {{ openvpn_user }}'
  args:
    creates: "/data/openvpn/keys/{{ openvpn_user }}.key"


- name: Get private key.
  shell: |
    docker exec openvpn \
    cat /etc/openvpn/keys/{{ openvpn_user }}.key
  register: openvpn_user_key

- name: Get public key.
  shell: |
    docker exec openvpn \
    cat /etc/openvpn/keys/{{ openvpn_user }}.crt
  register: openvpn_user_crt

- name: Get CA.
  shell: |
    docker exec openvpn \
    cat /etc/openvpn/keys/ca.crt
  register: openvpn_ca

- name: Template the OVPN config.
  template:
    src: openvpn.ovpn.j2
    dest: "/data/{{ openvpn_user }}.ovpn"

- name: Fetch OVPN config.
  fetch:
    src: /data/{{ openvpn_user }}.ovpn
    dest: "~/Desktop/{{ inventory_hostname }}-{{ openvpn_user }}.ovpn"
    flat: yes
