---
# openvpn.yml
#
# This playbook deploys an OpenVPN server to AWS.  Use the `vpc_create.yml`
#   if necessary to create the VPC, subnets, and routes.
#
# Example command:
#  ansible-playbook openvpn.yml -e "env=mod public_ip=true"
#
#####
# Initial AWS deployment
#####
- hosts: localhost
  connection: local
  gather_facts: yes

  vars_files:
    - "vars/{{ env }}_aws/aws.yml"
    - "vars/{{ env }}_aws/vault.yml"
    - vars/openvpn.yml

  roles:
    - role: localhost.ssh_key_configure
    - role: aws.vpc_facts
      filters:
        "tag:Environment": "{{ env }}"
    - role: aws.securitygroups
    - role: aws.iam
    - role: aws.ec2
    - role: aws.ec2_facts
      filters:
        "tag:Environment": "{{ env }}"
        instance-state-name: running
    - role: localhost.aws_ssh_keys
    - role: ansible.groups_init

#####
# Initial raw configuration
#####
- hosts: openvpn_public
  become: yes
  gather_facts: no
  user: ubuntu

  roles:
    - role: ubuntu.raw_install_python

#####
# Configure openvpn instance
#####
- hosts: openvpn_public
  become: yes
  gather_facts: yes
  remote_user: ubuntu

  vars_files:
    - vars/openvpn.yml

  roles:
    - role: instance.ssh_aws_public_key
    - role: instance.hosts
    - role: instance.automated_updates
      update_date: 'Tue, 07:00'
      reboot: true
    - role: instance.docker_install
    - role: instance.openvpn_configure
    - role: instance.openvpn_create_user_config
